import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import { Stripe } from 'stripe';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { Resend } from 'resend';

// ─── Init Firebase Admin ───────────────────────────────────────────
admin.initializeApp();
const db = admin.firestore();
const STORAGE_BUCKET = 'harvest-receipts-233a1';
const getBucket = () => admin.storage().bucket(STORAGE_BUCKET);

const SUPER_ADMIN_EMAILS = ['bumbmatei@proton.me', 'bumbmatei@zohomail.eu'];

// ─── Helper: generate single receipt PDF ───────────────────────────
async function generateReceiptPDF(invoice: any): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  const left = 50;
  let y = 800;

  page.drawText('Harvest', { x: left, y, size: 24, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 20;
  page.drawText('Donation Receipt', { x: left, y, size: 12, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 30;

  page.drawText(`Receipt #: ${invoice.receiptNumber || 'N/A'}`, { x: left, y, size: 10, font });
  y -= 16;
  const dateStr = invoice.issuedAt?.toDate
    ? invoice.issuedAt.toDate().toLocaleDateString('en-US')
    : new Date().toLocaleDateString('en-US');
  page.drawText(`Date: ${dateStr}`, { x: left, y, size: 10, font });
  y -= 16;
  page.drawText(`Tenant: ${invoice.tenantName || 'N/A'}`, { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Received from:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(invoice.recipientName || '', { x: left, y, size: 10, font });
  y -= 14;
  page.drawText(invoice.recipientEmail || '', { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Description:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(invoice.description || 'Donation', { x: left, y, size: 10, font });
  y -= 30;

  const currency = (invoice.currency || 'usd').toUpperCase();
  const amount = new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(invoice.amount / 100);
  page.drawText('Amount:', { x: left, y, size: 12, font: boldFont });
  page.drawText(amount, { x: 200, y, size: 12, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 40;

  page.drawText('This receipt is auto-generated by Harvest for tax purposes.', { x: left, y: 50, size: 8, font, color: rgb(0.6, 0.6, 0.6) });
  page.drawText('theharvest.app', { x: left, y: 35, size: 8, font, color: rgb(0.6, 0.6, 0.6) });

  return pdf.save();
}

// ─── Helper: generate annual receipt PDF ───────────────────────────
interface DonorData {
  name: string;
  email: string;
  total: number;
  donations: { date: Date; amount: number; description: string }[];
}

async function generateAnnualReceiptPDF(donor: DonorData, year: number): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  const left = 50;
  let y = 800;

  page.drawText('Harvest', { x: left, y, size: 24, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 20;
  page.drawText(`Annual Tax Receipt ${year}`, { x: left, y, size: 12, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 30;

  page.drawText('Donor:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(donor.name || donor.email, { x: left, y, size: 10, font });
  y -= 14;
  page.drawText(donor.email, { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Date', { x: left, y, size: 9, font: boldFont });
  page.drawText('Description', { x: 180, y, size: 9, font: boldFont });
  page.drawText('Amount', { x: 450, y, size: 9, font: boldFont });
  y -= 16;

  for (const d of donor.donations) {
    if (y < 100) break;
    page.drawText(d.date.toLocaleDateString('en-US'), { x: left, y, size: 9, font });
    page.drawText((d.description || 'Donation').slice(0, 35), { x: 180, y, size: 9, font });
    page.drawText(`$${(d.amount / 100).toFixed(2)}`, { x: 450, y, size: 9, font });
    y -= 14;
  }

  y -= 20;
  const totalStr = `$${(donor.total / 100).toFixed(2)}`;
  page.drawText('Total for year:', { x: 350, y, size: 12, font: boldFont });
  page.drawText(totalStr, { x: 450, y, size: 12, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 40;

  page.drawText('This document serves as your official tax receipt for the year specified.', { x: left, y: 50, size: 8, font, color: rgb(0.6, 0.6, 0.6) });
  page.drawText('theharvest.app', { x: left, y: 35, size: 8, font, color: rgb(0.6, 0.6, 0.6) });

  return pdf.save();
}

// ─── Helper: upsert contact ────────────────────────────────────────
async function upsertContact(opts: {
  tenantId: string;
  email: string;
  firstName?: string;
  lastName?: string;
  userId?: string;
  type?: 'donor' | 'member' | 'both';
}): Promise<string> {
  const { tenantId, email } = opts;
  const existing = await db.collection('contacts')
    .where('email', '==', email)
    .where('tenantId', '==', tenantId)
    .limit(1).get();

  if (!existing.empty) {
    const doc = existing.docs[0];
    const data = doc.data();
    const update: Record<string, any> = { updatedAt: admin.firestore.FieldValue.serverTimestamp() };
    if (opts.userId) update.userId = opts.userId;
    if (opts.type === 'donor' && data.type === 'member') update.type = 'both';
    else if (opts.type === 'member' && data.type === 'donor') update.type = 'both';
    else if (opts.type === 'both') update.type = 'both';
    await doc.ref.update(update);
    return doc.id;
  }

  const ref = await db.collection('contacts').add({
    firstName: opts.firstName || '',
    lastName: opts.lastName || '',
    email,
    phone: '',
    type: opts.type || 'member',
    userId: opts.userId || '',
    tenantId,
    totalDonated: 0,
    lastDonationAt: null,
    memberSince: opts.type === 'member' ? admin.firestore.FieldValue.serverTimestamp() : null,
    notes: '',
    tags: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    createdBy: 'system',
  });
  return ref.id;
}

// ─── 1. onUserCreated ───────────────────────────────────────────────
export const onUserCreated = functions.auth.user().onCreate(async (user) => {
  console.log(`onUserCreated: ${user.uid} (${user.email})`);

  await new Promise(resolve => setTimeout(resolve, 5000));

  const userDoc = await db.collection('users').doc(user.uid).get();
  if (!userDoc.exists) {
    console.log(`onUserCreated: No Firestore doc for ${user.uid} yet — will be caught by backfill`);
    return;
  }

  const userData = userDoc.data()!;
  const tenantId = userData.tenantId;
  if (!tenantId) {
    console.log(`onUserCreated: ${user.email} has no tenantId — skipping`);
    return;
  }

  const [firstName, ...lastNameParts] = (user.displayName || userData.firstName || '').split(' ');
  const lastName = lastNameParts.join(' ') || userData.lastName || '';

  const contactId = await upsertContact({
    tenantId,
    email: user.email || '',
    firstName: firstName || '',
    lastName,
    userId: user.uid,
    type: 'member',
  });

  console.log(`onUserCreated: CRM contact ${contactId} for ${user.email} in tenant ${tenantId}`);
});

// ─── 2. onPartnershipPayment ────────────────────────────────────────
export const onPartnershipPayment = functions.https.onRequest(async (req, res) => {
  if (req.method !== 'POST') {
    res.status(405).send('Method Not Allowed');
    return;
  }

  const stripeKey = process.env.STRIPE_SECRET_KEY;
  const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;
  if (!stripeKey || !webhookSecret) {
    console.error('onPartnershipPayment: Missing Stripe env vars');
    res.status(500).send('Stripe not configured');
    return;
  }

  const stripe = new Stripe(stripeKey);
  const sig = req.headers['stripe-signature'] as string;

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(req.rawBody!, sig, webhookSecret);
  } catch (err: any) {
    console.error('onPartnershipPayment: Signature verification failed:', err.message);
    res.status(400).send('Invalid signature');
    return;
  }

  if (event.type !== 'payment_intent.succeeded') {
    res.json({ received: true, ignored: true });
    return;
  }

  const pi = event.data.object as Stripe.PaymentIntent;
  const meta = pi.metadata || {};

  if (meta.type !== 'partnership') {
    res.json({ received: true, ignored: 'non-partnership' });
    return;
  }

  const tenantId = meta.tenantId;
  const donorEmail = pi.receipt_email || meta.donorEmail || '';
  const amount = pi.amount_received || pi.amount || 0;

  if (!tenantId || !donorEmail) {
    res.json({ received: true, skipped: 'missing metadata' });
    return;
  }

  console.log(`onPartnershipPayment: $${(amount / 100).toFixed(2)} from ${donorEmail} for tenant ${tenantId}`);

  const contactId = await upsertContact({
    tenantId,
    email: donorEmail,
    type: 'donor',
  });

  await db.collection('contacts').doc(contactId).update({
    totalDonated: admin.firestore.FieldValue.increment(amount),
    lastDonationAt: admin.firestore.FieldValue.serverTimestamp(),
  });

  await db.collection('contactActivities').add({
    contactId,
    type: 'donation',
    description: 'Partnership donation via Stripe',
    amount,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    createdBy: 'system',
  });

  const tenantDoc = await db.collection('tenants').doc(tenantId).get();
  const tenantName = tenantDoc.data()?.name || tenantDoc.data()?.displayName || '';

  const contactDoc = await db.collection('contacts').doc(contactId).get();
  const cData = contactDoc.data() || {};
  const recipientName = `${cData.firstName || ''} ${cData.lastName || ''}`.trim() || donorEmail;

  const receiptNumber = `R-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
  await db.collection('tenants').doc(tenantId).collection('invoices').add({
    type: 'donation_receipt',
    recipientName,
    recipientEmail: donorEmail,
    amount,
    currency: pi.currency || 'usd',
    description: 'Partnership donation',
    relatedId: pi.id,
    receiptNumber,
    issuedAt: admin.firestore.FieldValue.serverTimestamp(),
    tenantName,
    pdfUrl: null,
    status: 'pending',
  });

  console.log(`onPartnershipPayment: Created invoice + activity for ${donorEmail}`);
  res.json({ received: true, processed: true, contactId });
});

// ─── 3. backfillCRMContacts ─────────────────────────────────────────
export const backfillCRMContacts = functions.https.onCall(async (_data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Must be signed in');
  }

  const uid = context.auth.uid;
  const email = context.auth.token.email || '';
  const userDoc = await db.collection('users').doc(uid).get();
  const userData = userDoc.data();

  const isSuperAdmin = SUPER_ADMIN_EMAILS.includes(email)
    || userData?.role === 'super_admin'
    || context.auth.token.superAdmin === true;

  if (!isSuperAdmin) {
    throw new functions.https.HttpsError('permission-denied', 'Super admin only');
  }

  console.log('backfillCRMContacts: Starting backfill...');

  const usersSnap = await db.collection('users').get();
  let created = 0, updated = 0, skipped = 0;

  for (const doc of usersSnap.docs) {
    const data = doc.data();
    const tenantId = data.tenantId;
    const userEmail = data.email || '';
    if (!tenantId || !userEmail) { skipped++; continue; }

    // Check if contact already exists
    const existingSnap = await db.collection('contacts')
      .where('email', '==', userEmail)
      .where('tenantId', '==', tenantId)
      .limit(1).get();

    const wasNew = existingSnap.empty;

    const [firstName, ...lastNameParts] = (data.displayName || data.firstName || '').split(' ');
    await upsertContact({
      tenantId,
      email: userEmail,
      firstName: firstName || '',
      lastName: lastNameParts.join(' ') || '',
      userId: doc.id,
      type: 'member',
    });

    if (wasNew) created++;
    else updated++;
  }

  const result = { created, updated, skipped, total: usersSnap.size };
  console.log('backfillCRMContacts: Done', result);
  return result;
});

// ─── 4. generateSingleReceipt ───────────────────────────────────────
export const generateSingleReceipt = functions.firestore
  .document('tenants/{tenantId}/invoices/{invoiceId}')
  .onCreate(async (snap, context) => {
    const invoiceData = snap.data();
    const tenantId = context.params.tenantId;
    const invoiceId = context.params.invoiceId;

    console.log(`generateSingleReceipt: Generating PDF for invoice ${invoiceId} in tenant ${tenantId}`);

    try {
      const pdfBytes = await generateReceiptPDF(invoiceData);

      const bucket = getBucket();
      const filePath = `tenants/${tenantId}/invoices/${invoiceId}.pdf`;
      const file = bucket.file(filePath);
      await file.save(Buffer.from(pdfBytes), { metadata: { contentType: 'application/pdf' } });
      await file.makePublic();

      const pdfUrl = `https://storage.googleapis.com/${bucket.name}/${filePath}`;

      await snap.ref.update({
        pdfUrl,
        status: 'generated',
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      });

      console.log(`generateSingleReceipt: PDF generated and uploaded for ${invoiceId}`);
    } catch (error: any) {
      console.error(`generateSingleReceipt: Failed for ${invoiceId}:`, error?.message || error);
    }
  });

// ─── 5. generateAnnualReceipts ──────────────────────────────────────
export const generateAnnualReceipts = functions.https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Must be signed in');
  }

  const { year, tenantId } = data;
  if (!year || !tenantId) {
    throw new functions.https.HttpsError('invalid-argument', 'year and tenantId required');
  }

  const uid = context.auth.uid;
  const email = context.auth.token.email || '';
  const userDoc = await db.collection('users').doc(uid).get();
  const userData = userDoc.data();

  const isSuperAdmin = SUPER_ADMIN_EMAILS.includes(email)
    || userData?.role === 'super_admin'
    || context.auth.token.superAdmin === true;

  if (!isSuperAdmin && userData?.tenantId !== tenantId) {
    throw new functions.https.HttpsError('permission-denied', 'Access denied to this tenant');
  }

  console.log(`generateAnnualReceipts: year=${year}, tenantId=${tenantId}`);

  const startOfYear = new Date(Number(year), 0, 1);
  const endOfYear = new Date(Number(year), 11, 31, 23, 59, 59);

  const invoicesSnap = await db.collection('tenants').doc(tenantId)
    .collection('invoices')
    .where('type', '==', 'donation_receipt')
    .where('issuedAt', '>=', startOfYear)
    .where('issuedAt', '<=', endOfYear)
    .get();

  if (invoicesSnap.empty) {
    return { generated: 0, sent: 0, totalDonors: 0, message: 'No donation invoices found for this year' };
  }

  const tenantDoc = await db.collection('tenants').doc(tenantId).get();
  const tenantName = tenantDoc.data()?.name || tenantDoc.data()?.displayName || '';

  // Group by donor email
  const donorsMap = new Map<string, DonorData>();

  for (const doc of invoicesSnap.docs) {
    const inv = doc.data();
    const donorEmail = inv.recipientEmail;
    if (!donorEmail) continue;
    if (!donorsMap.has(donorEmail)) {
      donorsMap.set(donorEmail, {
        name: inv.recipientName || donorEmail,
        email: donorEmail,
        total: 0,
        donations: [],
      });
    }
    const donor = donorsMap.get(donorEmail)!;
    donor.total += inv.amount;
    donor.donations.push({
      date: inv.issuedAt?.toDate ? inv.issuedAt.toDate() : new Date(),
      amount: inv.amount,
      description: inv.description || 'Donation',
    });
  }

  const bucket = getBucket();
  let sent = 0, generated = 0;
  const failedEmails: string[] = [];

  for (const [email, donor] of donorsMap) {
    try {
      const pdfBytes = await generateAnnualReceiptPDF(donor, Number(year));

      const filePath = `tenants/${tenantId}/annual-receipts/${year}/${email}.pdf`;
      const file = bucket.file(filePath);
      await file.save(Buffer.from(pdfBytes), { metadata: { contentType: 'application/pdf' } });
      await file.makePublic();

      generated++;

      const resendKey = process.env.RESEND_API_KEY;
      if (resendKey) {
        const resend = new Resend(resendKey);
        const pdfBase64 = Buffer.from(pdfBytes).toString('base64');

        const { error } = await resend.emails.send({
          from: 'Harvest <noreply@theharvest.app>',
          to: email,
          subject: `Annual Tax Receipt ${year} — ${tenantName || 'Harvest'}`,
          html: `<p>Dear ${donor.name},</p><p>Please find your annual tax receipt attached for the year ${year}.</p><p>Total donations: <strong>$${(donor.total / 100).toFixed(2)}</strong></p><p>Thank you for your partnership!</p><br><p>— ${tenantName || 'Harvest'}</p>`,
          attachments: [{ filename: `tax-receipt-${year}.pdf`, content: pdfBase64 }],
        });

        if (error) {
          console.error(`generateAnnualReceipts: Failed to email ${email}:`, error);
          failedEmails.push(email);
        } else {
          sent++;
        }
      } else {
        console.log('generateAnnualReceipts: No Resend key — PDF generated but not emailed');
      }
    } catch (err: any) {
      console.error(`generateAnnualReceipts: Failed for ${email}:`, err?.message || err);
      failedEmails.push(email);
    }
  }

  const result = { generated, sent, totalDonors: donorsMap.size, failedEmails };
  console.log('generateAnnualReceipts: Done', result);
  return result;
});