import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import { Stripe } from 'stripe';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { Resend } from 'resend';

// ─── Init Firebase Admin ───────────────────────────────────────────
admin.initializeApp();
const db = admin.firestore();
const STORAGE_BUCKET = 'harvest-receipts-233a1';
const getBucket = () => admin.storage().bucket(STORAGE_BUCKET);

const SUPER_ADMIN_EMAILS = ['bumbmatei@proton.me', 'bumbmatei@zohomail.eu'];

// ─── Helper: generate single receipt PDF ───────────────────────────
async function generateReceiptPDF(invoice: any): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  const left = 50;
  let y = 800;

  page.drawText('Harvest', { x: left, y, size: 24, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 20;
  page.drawText('Donation Receipt', { x: left, y, size: 12, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 30;

  page.drawText(`Receipt #: ${invoice.receiptNumber || 'N/A'}`, { x: left, y, size: 10, font });
  y -= 16;
  const dateStr = invoice.issuedAt?.toDate
    ? invoice.issuedAt.toDate().toLocaleDateString('en-US')
    : new Date().toLocaleDateString('en-US');
  page.drawText(`Date: ${dateStr}`, { x: left, y, size: 10, font });
  y -= 16;
  page.drawText(`Tenant: ${invoice.tenantName || 'N/A'}`, { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Received from:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(invoice.recipientName || '', { x: left, y, size: 10, font });
  y -= 14;
  page.drawText(invoice.recipientEmail || '', { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Description:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(invoice.description || 'Donation', { x: left, y, size: 10, font });
  y -= 30;

  const currency = (invoice.currency || 'usd').toUpperCase();
  const amount = new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(invoice.amount / 100);
  page.drawText('Amount:', { x: left, y, size: 12, font: boldFont });
  page.drawText(amount, { x: 200, y, size: 12, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 40;

  page.drawText('This receipt is auto-generated by Harvest for tax purposes.', { x: left, y: 50, size: 8, font, color: rgb(0.6, 0.6, 0.6) });
  page.drawText('theharvest.app', { x: left, y: 35, size: 8, font, color: rgb(0.6, 0.6, 0.6) });

  return pdf.save();
}

// ─── Helper: generate annual receipt PDF ───────────────────────────
interface DonorData {
  name: string;
  email: string;
  total: number;
  donations: { date: Date; amount: number; description: string }[];
}

async function generateAnnualReceiptPDF(donor: DonorData, year: number): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  const left = 50;
  let y = 800;

  page.drawText('Harvest', { x: left, y, size: 24, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 20;
  page.drawText(`Annual Tax Receipt ${year}`, { x: left, y, size: 12, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 30;

  page.drawText('Donor:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(donor.name || donor.email, { x: left, y, size: 10, font });
  y -= 14;
  page.drawText(donor.email, { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Date', { x: left, y, size: 9, font: boldFont });
  page.drawText('Description', { x: 180, y, size: 9, font: boldFont });
  page.drawText('Amount', { x: 450, y, size: 9, font: boldFont });
  y -= 16;

  for (const d of donor.donations) {
    if (y < 100) break;
    page.drawText(d.date.toLocaleDateString('en-US'), { x: left, y, size: 9, font });
    page.drawText((d.description || 'Donation').slice(0, 35), { x: 180, y, size: 9, font });
    page.drawText(`$${(d.amount / 100).toFixed(2)}`, { x: 450, y, size: 9, font });
    y -= 14;
  }

  y -= 20;
  const totalStr = `$${(donor.total / 100).toFixed(2)}`;
  page.drawText('Total for year:', { x: 350, y, size: 12, font: boldFont });
  page.drawText(totalStr, { x: 450, y, size: 12, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 40;

  page.drawText('This document serves as your official tax receipt for the year specified.', { x: left, y: 50, size: 8, font, color: rgb(0.6, 0.6, 0.6) });
  page.drawText('theharvest.app', { x: left, y: 35, size: 8, font, color: rgb(0.6, 0.6, 0.6) });

  return pdf.save();
}

// ─── Helper: upsert contact ────────────────────────────────────────
async function upsertContact(opts: {
  tenantId: string;
  email: string;
  firstName?: string;
  lastName?: string;
  userId?: string;
  type?: 'donor' | 'member' | 'both';
}): Promise<string> {
  const { tenantId, email } = opts;
  const existing = await db.collection('contacts')
    .where('email', '==', email)
    .where('tenantId', '==', tenantId)
    .limit(1).get();

  if (!existing.empty) {
    const doc = existing.docs[0];
    const data = doc.data();
    const update: Record<string, any> = { updatedAt: admin.firestore.FieldValue.serverTimestamp() };
    if (opts.userId) update.userId = opts.userId;
    if (opts.type === 'donor' && data.type === 'member') update.type = 'both';
    else if (opts.type === 'member' && data.type === 'donor') update.type = 'both';
    else if (opts.type === 'both') update.type = 'both';
    await doc.ref.update(update);
    return doc.id;
  }

  const ref = await db.collection('contacts').add({
    firstName: opts.firstName || '',
    lastName: opts.lastName || '',
    email,
    phone: '',
    type: opts.type || 'member',
    userId: opts.userId || '',
    tenantId,
    totalDonated: 0,
    lastDonationAt: null,
    memberSince: opts.type === 'member' ? admin.firestore.FieldValue.serverTimestamp() : null,
    notes: '',
    tags: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    createdBy: 'system',
  });
  return ref.id;
}

// ─── 1. onUserCreated ───────────────────────────────────────────────
export const onUserCreated = functions.auth.user().onCreate(async (user) => {
  console.log(`onUserCreated: ${user.uid} (${user.email})`);

  await new Promise(resolve => setTimeout(resolve, 5000));

  const userDoc = await db.collection('users').doc(user.uid).get();
  if (!userDoc.exists) {
    console.log(`onUserCreated: No Firestore doc for ${user.uid} yet — will be caught by backfill`);
    return;
  }

  const userData = userDoc.data()!;
  const tenantId = userData.tenantId;
  if (!tenantId) {
    console.log(`onUserCreated: ${user.email} has no tenantId — skipping`);
    return;
  }

  const [firstName, ...lastNameParts] = (user.displayName || userData.firstName || '').split(' ');
  const lastName = lastNameParts.join(' ') || userData.lastName || '';

  const contactId = await upsertContact({
    tenantId,
    email: user.email || '',
    firstName: firstName || '',
    lastName,
    userId: user.uid,
    type: 'member',
  });

  console.log(`onUserCreated: CRM contact ${contactId} for ${user.email} in tenant ${tenantId}`);
});

// ─── 2. onPartnershipPayment ────────────────────────────────────────
export const onPartnershipPayment = functions.https.onRequest(async (req, res) => {
  if (req.method !== 'POST') {
    res.status(405).send('Method Not Allowed');
    return;
  }

  const stripeKey = process.env.STRIPE_SECRET_KEY;
  const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;
  if (!stripeKey || !webhookSecret) {
    console.error('onPartnershipPayment: Missing Stripe env vars');
    res.status(500).send('Stripe not configured');
    return;
  }

  const stripe = new Stripe(stripeKey);
  const sig = req.headers['stripe-signature'] as string;

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(req.rawBody!, sig, webhookSecret);
  } catch (err: any) {
    console.error('onPartnershipPayment: Signature verification failed:', err.message);
    res.status(400).send('Invalid signature');
    return;
  }

  if (event.type !== 'payment_intent.succeeded') {
    res.json({ received: true, ignored: true });
    return;
  }

  const pi = event.data.object as Stripe.PaymentIntent;
  const meta = pi.metadata || {};

  if (meta.type !== 'partnership') {
    res.json({ received: true, ignored: 'non-partnership' });
    return;
  }

  const tenantId = meta.tenantId;
  const donorEmail = pi.receipt_email || meta.donorEmail || '';
  const amount = pi.amount_received || pi.amount || 0;

  if (!tenantId || !donorEmail) {
    res.json({ received: true, skipped: 'missing metadata' });
    return;
  }

  console.log(`onPartnershipPayment: $${(amount / 100).toFixed(2)} from ${donorEmail} for tenant ${tenantId}`);

  const contactId = await upsertContact({
    tenantId,
    email: donorEmail,
    type: 'donor',
  });

  await db.collection('contacts').doc(contactId).update({
    totalDonated: admin.firestore.FieldValue.increment(amount),
    lastDonationAt: admin.firestore.FieldValue.serverTimestamp(),
  });

  await db.collection('contactActivities').add({
    contactId,
    type: 'donation',
    description: 'Partnership donation via Stripe',
    amount,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    createdBy: 'system',
  });

  const tenantDoc = await db.collection('tenants').doc(tenantId).get();
  const tenantName = tenantDoc.data()?.name || tenantDoc.data()?.displayName || '';

  const contactDoc = await db.collection('contacts').doc(contactId).get();
  const cData = contactDoc.data() || {};
  const recipientName = `${cData.firstName || ''} ${cData.lastName || ''}`.trim() || donorEmail;

  const receiptNumber = `R-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
  await db.collection('tenants').doc(tenantId).collection('invoices').add({
    type: 'donation_receipt',
    recipientName,
    recipientEmail: donorEmail,
    amount,
    currency: pi.currency || 'usd',
    description: 'Partnership donation',
    relatedId: pi.id,
    receiptNumber,
    issuedAt: admin.firestore.FieldValue.serverTimestamp(),
    tenantName,
    pdfUrl: null,
    status: 'pending',
  });

  console.log(`onPartnershipPayment: Created invoice + activity for ${donorEmail}`);
  res.json({ received: true, processed: true, contactId });
});

// ─── 3. backfillCRMContacts ─────────────────────────────────────────
export const backfillCRMContacts = functions.https.onCall(async (_data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Must be signed in');
  }

  const uid = context.auth.uid;
  const email = context.auth.token.email || '';
  const userDoc = await db.collection('users').doc(uid).get();
  const userData = userDoc.data();

  const isSuperAdmin = SUPER_ADMIN_EMAILS.includes(email)
    || userData?.role === 'super_admin'
    || context.auth.token.superAdmin === true;

  if (!isSuperAdmin) {
    throw new functions.https.HttpsError('permission-denied', 'Super admin only');
  }

  console.log('backfillCRMContacts: Starting backfill...');

  const usersSnap = await db.collection('users').get();
  let created = 0, updated = 0, skipped = 0;

  for (const doc of usersSnap.docs) {
    const data = doc.data();
    const tenantId = data.tenantId;
    const userEmail = data.email || '';
    if (!tenantId || !userEmail) { skipped++; continue; }

    // Check if contact already exists
    const existingSnap = await db.collection('contacts')
      .where('email', '==', userEmail)
      .where('tenantId', '==', tenantId)
      .limit(1).get();

    const wasNew = existingSnap.empty;

    const [firstName, ...lastNameParts] = (data.displayName || data.firstName || '').split(' ');
    await upsertContact({
      tenantId,
      email: userEmail,
      firstName: firstName || '',
      lastName: lastNameParts.join(' ') || '',
      userId: doc.id,
      type: 'member',
    });

    if (wasNew) created++;
    else updated++;
  }

  const result = { created, updated, skipped, total: usersSnap.size };
  console.log('backfillCRMContacts: Done', result);
  return result;
});

// ─── 4. generateSingleReceipt ───────────────────────────────────────
export const generateSingleReceipt = functions.firestore
  .document('tenants/{tenantId}/invoices/{invoiceId}')
  .onCreate(async (snap, context) => {
    const invoiceData = snap.data();
    const tenantId = context.params.tenantId;
    const invoiceId = context.params.invoiceId;

    console.log(`generateSingleReceipt: Generating PDF for invoice ${invoiceId} in tenant ${tenantId}`);

    try {
      const pdfBytes = await generateReceiptPDF(invoiceData);

      const bucket = getBucket();
      const filePath = `tenants/${tenantId}/invoices/${invoiceId}.pdf`;
      const file = bucket.file(filePath);
      await file.save(Buffer.from(pdfBytes), { metadata: { contentType: 'application/pdf' } });
      await file.makePublic();

      const pdfUrl = `https://storage.googleapis.com/${bucket.name}/${filePath}`;

      await snap.ref.update({
        pdfUrl,
        status: 'generated',
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      });

      console.log(`generateSingleReceipt: PDF generated and uploaded for ${invoiceId}`);
    } catch (error: any) {
      console.error(`generateSingleReceipt: Failed for ${invoiceId}:`, error?.message || error);
    }
  });

// ─── 5. generateAnnualReceipts ──────────────────────────────────────
export const generateAnnualReceipts = functions.https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Must be signed in');
  }

  const { year, tenantId } = data;
  if (!year || !tenantId) {
    throw new functions.https.HttpsError('invalid-argument', 'year and tenantId required');
  }

  const uid = context.auth.uid;
  const email = context.auth.token.email || '';
  const userDoc = await db.collection('users').doc(uid).get();
  const userData = userDoc.data();

  const isSuperAdmin = SUPER_ADMIN_EMAILS.includes(email)
    || userData?.role === 'super_admin'
    || context.auth.token.superAdmin === true;

  if (!isSuperAdmin && userData?.tenantId !== tenantId) {
    throw new functions.https.HttpsError('permission-denied', 'Access denied to this tenant');
  }

  console.log(`generateAnnualReceipts: year=${year}, tenantId=${tenantId}`);

  const startOfYear = new Date(Number(year), 0, 1);
  const endOfYear = new Date(Number(year), 11, 31, 23, 59, 59);

  const invoicesSnap = await db.collection('tenants').doc(tenantId)
    .collection('invoices')
    .where('type', '==', 'donation_receipt')
    .where('issuedAt', '>=', startOfYear)
    .where('issuedAt', '<=', endOfYear)
    .get();

  if (invoicesSnap.empty) {
    return { generated: 0, sent: 0, totalDonors: 0, message: 'No donation invoices found for this year' };
  }

  const tenantDoc = await db.collection('tenants').doc(tenantId).get();
  const tenantName = tenantDoc.data()?.name || tenantDoc.data()?.displayName || '';

  // Group by donor email
  const donorsMap = new Map<string, DonorData>();

  for (const doc of invoicesSnap.docs) {
    const inv = doc.data();
    const donorEmail = inv.recipientEmail;
    if (!donorEmail) continue;
    if (!donorsMap.has(donorEmail)) {
      donorsMap.set(donorEmail, {
        name: inv.recipientName || donorEmail,
        email: donorEmail,
        total: 0,
        donations: [],
      });
    }
    const donor = donorsMap.get(donorEmail)!;
    donor.total += inv.amount;
    donor.donations.push({
      date: inv.issuedAt?.toDate ? inv.issuedAt.toDate() : new Date(),
      amount: inv.amount,
      description: inv.description || 'Donation',
    });
  }

  const bucket = getBucket();
  let sent = 0, generated = 0;
  const failedEmails: string[] = [];

  for (const [email, donor] of donorsMap) {
    try {
      const pdfBytes = await generateAnnualReceiptPDF(donor, Number(year));

      const filePath = `tenants/${tenantId}/annual-receipts/${year}/${email}.pdf`;
      const file = bucket.file(filePath);
      await file.save(Buffer.from(pdfBytes), { metadata: { contentType: 'application/pdf' } });
      await file.makePublic();

      generated++;

      const resendKey = process.env.RESEND_API_KEY;
      if (resendKey) {
        const resend = new Resend(resendKey);
        const pdfBase64 = Buffer.from(pdfBytes).toString('base64');

        const { error } = await resend.emails.send({
          from: 'Harvest <noreply@theharvest.app>',
          to: email,
          subject: `Annual Tax Receipt ${year} — ${tenantName || 'Harvest'}`,
          html: `<p>Dear ${donor.name},</p><p>Please find your annual tax receipt attached for the year ${year}.</p><p>Total donations: <strong>$${(donor.total / 100).toFixed(2)}</strong></p><p>Thank you for your partnership!</p><br><p>— ${tenantName || 'Harvest'}</p>`,
          attachments: [{ filename: `tax-receipt-${year}.pdf`, content: pdfBase64 }],
        });

        if (error) {
          console.error(`generateAnnualReceipts: Failed to email ${email}:`, error);
          failedEmails.push(email);
        } else {
          sent++;
        }
      } else {
        console.log('generateAnnualReceipts: No Resend key — PDF generated but not emailed');
      }
    } catch (err: any) {
      console.error(`generateAnnualReceipts: Failed for ${email}:`, err?.message || err);
      failedEmails.push(email);
    }
  }

  const result = { generated, sent, totalDonors: donorsMap.size, failedEmails };
  console.log('generateAnnualReceipts: Done', result);
  return result;
});

// ─── 6. addChurchBilling ────────────────────────────────────────────
// Called from the client after a new church is created on an Organization plan.
// Adds a $15/mo subscription item to the tenant's existing Stripe subscription.
export const addChurchBilling = functions.https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Must be signed in');
  }

  const { tenantId, churchId, churchName } = data;
  if (!tenantId || !churchId) {
    throw new functions.https.HttpsError('invalid-argument', 'tenantId and churchId required');
  }

  const uid = context.auth.uid;
  const email = context.auth.token.email || '';
  const userDoc = await db.collection('users').doc(uid).get();
  const userData = userDoc.data();

  const isSuperAdmin = SUPER_ADMIN_EMAILS.includes(email)
    || userData?.role === 'super_admin'
    || context.auth.token.superAdmin === true;

  // Verify the user belongs to this tenant (or is super admin)
  if (!isSuperAdmin && userData?.tenantId !== tenantId) {
    throw new functions.https.HttpsError('permission-denied', 'Access denied to this tenant');
  }

  const stripeKey = process.env.STRIPE_SECRET_KEY;
  if (!stripeKey) {
    throw new functions.https.HttpsError('failed-precondition', 'Stripe not configured');
  }
  const stripe = new Stripe(stripeKey);

  const tenantDoc = await db.collection('tenants').doc(tenantId).get();
  const tenantData = tenantDoc.data();
  if (!tenantData) {
    throw new functions.https.HttpsError('not-found', 'Tenant not found');
  }

  const subscriptionId = tenantData?.stripeSubscriptionId;
  if (!subscriptionId) {
    throw new functions.https.HttpsError('failed-precondition', 'Tenant has no active Stripe subscription');
  }

  console.log(`addChurchBilling: Adding $15/mo for church ${churchId} on subscription ${subscriptionId}`);

  // Create subscription item with inline price_data (no pre-created product needed)
  const subItem = await stripe.subscriptionItems.create({
    subscription: subscriptionId,
    price_data: {
      currency: 'usd',
      unit_amount: 1500, // $15.00/mo
      recurring: { interval: 'month' },
      product_data: {
        name: `Additional Church: ${churchName || churchId}`,
        metadata: { tenantId, churchId, type: 'per_church' },
      },
    } as any,
    metadata: {
      tenantId,
      churchId,
      type: 'per_church',
    },
  });

  // Store the subscription item ID on the church document
  await db.collection('churches').doc(churchId).update({
    stripeSubscriptionItemId: subItem.id,
    billingAmount: 1500,
    billingAddedAt: admin.firestore.FieldValue.serverTimestamp(),
  });

  console.log(`addChurchBilling: Created subscription item ${subItem.id} for church ${churchId}`);
  return { success: true, subscriptionItemId: subItem.id };
});

// ─── 7. removeChurchBilling ────────────────────────────────────────
// Triggered when a church document is deleted — removes the $15/mo
// subscription item from the tenant's Stripe subscription automatically.
export const removeChurchBilling = functions.firestore
  .document('churches/{churchId}')
  .onDelete(async (snap, context) => {
    const churchData = snap.data();
    if (!churchData) return;

    const subscriptionItemId = churchData.stripeSubscriptionItemId;
    if (!subscriptionItemId) {
      console.log(`removeChurchBilling: Church ${context.params.churchId} has no subscription item — skipping`);
      return;
    }

    const stripeKey = process.env.STRIPE_SECRET_KEY;
    if (!stripeKey) {
      console.error('removeChurchBilling: STRIPE_SECRET_KEY not configured');
      return;
    }
    const stripe = new Stripe(stripeKey);

    try {
      await stripe.subscriptionItems.del(subscriptionItemId);
      console.log(`removeChurchBilling: Removed subscription item ${subscriptionItemId} for deleted church ${context.params.churchId}`);
    } catch (err: any) {
      console.error(`removeChurchBilling: Failed to remove subscription item ${subscriptionItemId}:`, err?.message || err);
      // Don't throw — the church is already deleted, we don't want to block deletion
    }
  });

// ─── 8. telegramWebhook ─────────────────────────────────────────────────
// HTTP webhook endpoint for the Harvest AI Assistant Telegram bot.
// Telegram sends updates here when a user sends a message to the bot.
export const telegramWebhook = functions.https.onRequest(async (req, res) => {
  if (req.method !== 'POST') {
    res.status(200).json({ ok: true });
    return;
  }

  const update = req.body;
  console.log('telegramWebhook: Received update', JSON.stringify(update).slice(0, 200));

  try {
    const message = update.message;
    if (!message || !message.text) {
      res.status(200).json({ ok: true });
      return;
    }

    const chatId = message.chat.id;
    const text = message.text.trim();
    const fromUser = message.from;
    const userId = fromUser?.id?.toString() || '';
    const username = fromUser?.username || '';

    console.log(`telegramWebhook: Message from ${userId} (${username}): ${text.slice(0, 100)}`);

    // ── /start ──
    if (text.startsWith('/start')) {
      await sendTelegramMessage(chatId,
        '👋 Welcome to the Harvest AI Assistant!\n\n' +
        'To connect your account, reply with your access code.\n\n' +
        'Example: `ABC-DEF-123`\n\n' +
        "If you don't have an access code, please contact your Harvest admin."
      );
      res.status(200).json({ ok: true });
      return;
    }

    // ── /help ──
    if (text.startsWith('/help')) {
      await sendTelegramMessage(chatId,
        '🤖 *Harvest AI Assistant Help*\n\n' +
        'Commands:\n' +
        '/start — Get started with your access code\n' +
        '/status — Check your subscription status\n' +
        '/help — Show this help message\n\n' +
        'Or reply with your access code to connect your account.'
      );
      res.status(200).json({ ok: true });
      return;
    }

    // ── /status ──
    if (text.startsWith('/status')) {
      const bindingSnap = await db.collection('ai_assistant_bindings')
        .where('telegramUserId', '==', userId).limit(1).get();

      if (bindingSnap.empty) {
        await sendTelegramMessage(chatId, '⚠️ No active AI Assistant subscription found.\n\nReply with your access code to get started.');
        res.status(200).json({ ok: true });
        return;
      }

      const binding = bindingSnap.docs[0].data();
      const tenantDoc = await db.collection('tenants').doc(binding.tenantId).get();
      const tenantData = tenantDoc.data();
      const active = !!tenantData?.addOnAiAssistant;

      const reply = active
        ? `✅ *AI Assistant Active*\n\nTenant: ${tenantData?.name || 'Unknown'}\nPlan: ${tenantData?.plan || 'Ministry'}\nStatus: Active`
        : `❌ *AI Assistant Subscription Inactive*\n\nYour AI Assistant subscription has expired or been cancelled.\nContact your administrator to reactivate.`;

      await sendTelegramMessage(chatId, reply);
      res.status(200).json({ ok: true });
      return;
    }

    // ── Access code verification ──
    const codePattern = /^[A-Z]{2,5}-[A-Z0-9]{3,5}-[A-Z0-9]{3,5}$/i;
    const upperCode = text.toUpperCase().replace(/\s+/g, '-');

    if (codePattern.test(upperCode) || (text.length >= 9 && text.length <= 20)) {
      const tenantsSnap = await db.collection('tenants')
        .where('addOnAiAssistantCode', '==', upperCode).limit(1).get();

      if (tenantsSnap.empty) {
        await sendTelegramMessage(chatId, '❌ Invalid access code. Please check and try again.');
        res.status(200).json({ ok: true });
        return;
      }

      const tenantDoc = tenantsSnap.docs[0];
      const tenantData = tenantDoc.data();
      const tenantId = tenantDoc.id;

      if (!tenantData.addOnAiAssistant) {
        await sendTelegramMessage(chatId, '⚠️ Code found but AI Assistant subscription is inactive.');
        res.status(200).json({ ok: true });
        return;
      }

      const existingBinding = await db.collection('ai_assistant_bindings')
        .where('telegramUserId', '==', userId).limit(1).get();

      if (!existingBinding.empty) {
        const binding = existingBinding.docs[0].data();
        if (binding.tenantId === tenantId) {
          await sendTelegramMessage(chatId, `✅ You're already connected to *${tenantData.name}*.\n\nReply /status to check your subscription.`);
          res.status(200).json({ ok: true });
          return;
        }
        await sendTelegramMessage(chatId, '⚠️ This Telegram account is already bound to another organization.');
        res.status(200).json({ ok: true });
        return;
      }

      await db.collection('ai_assistant_bindings').add({
        tenantId,
        telegramUserId: userId,
        telegramUsername: username || null,
        code: upperCode,
        boundAt: admin.firestore.FieldValue.serverTimestamp(),
      });

      await sendTelegramMessage(chatId,
        `✅ *Access Granted!*\n\nConnected to: *${tenantData.name}*\nSubscription: AI Assistant\nPlan: ${tenantData.plan || 'Ministry'}\n\nReply /help for available commands.`
      );
      res.status(200).json({ ok: true, verified: true });
      return;
    }

    // ── Default ──
    await sendTelegramMessage(chatId,
      "❓ I didn't understand that.\n\n" +
      'Reply with your access code (e.g. `ABC-DEF-123`), or use:\n' +
      '/status — Check your subscription\n' +
      '/help — Show all commands'
    );
    res.status(200).json({ ok: true });
  } catch (err: any) {
    console.error('telegramWebhook error:', err?.message || err);
    res.status(200).json({ ok: false, error: err?.message || 'Internal error' });
  }
});

// ─── Helper: send Telegram message via Bot API ─────────────────────────
async function sendTelegramMessage(chatId: number | string, text: string): Promise<void> {
  const botToken = process.env.TELEGRAM_BOT_TOKEN;
  if (!botToken) {
    console.error('sendTelegramMessage: TELEGRAM_BOT_TOKEN not set');
    return;
  }

  const https = require('https');
  const data = JSON.stringify({ chat_id: chatId, text, parse_mode: 'Markdown' });

  try {
    await new Promise<void>((resolve, reject) => {
      const req = https.request(
        `https://api.telegram.org/bot${botToken}/sendMessage`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Content-Length': data.length },
          timeout: 10000,
        },
        (res: any) => {
          let body = '';
          res.on('data', (chunk: any) => { body += chunk; });
          res.on('end', () => {
            if (res.statusCode >= 200 && res.statusCode < 300) {
              console.log(`sendTelegramMessage: Sent to ${chatId}`);
              resolve();
            } else {
              console.error(`sendTelegramMessage: Got ${res.statusCode}: ${body}`);
              reject(new Error(`Telegram API returned ${res.statusCode}`));
            }
          });
        }
      );
      req.on('error', reject);
      req.write(data);
      req.end();
    });
  } catch (err: any) {
    console.error('sendTelegramMessage: Failed:', err?.message || err);
  }
}