import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import { Stripe } from 'stripe';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { Resend } from 'resend';

// ─── Init Firebase Admin ──────────────────────────────────────────────────
admin.initializeApp();
const db = admin.firestore();
const STORAGE_BUCKET = 'harvest-receipts-233a1';
const getBucket = () => admin.storage().bucket(STORAGE_BUCKET);

const SUPER_ADMIN_EMAILS = ['bumbmatei@proton.me', 'bumbmatei@zohomail.eu'];

// ─── Helper: generate single receipt PDF ───────────────────────────────────
async function generateReceiptPDF(invoice: any): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  const left = 50;
  let y = 800;

  page.drawText('Harvest', { x: left, y, size: 24, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 20;
  page.drawText('Donation Receipt', { x: left, y, size: 12, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 30;

  page.drawText(`Receipt #: ${invoice.receiptNumber || 'N/A'}`, { x: left, y, size: 10, font });
  y -= 16;
  const dateStr = invoice.issuedAt?.toDate
    ? invoice.issuedAt.toDate().toLocaleDateString('en-US')
    : new Date().toLocaleDateString('en-US');
  page.drawText(`Date: ${dateStr}`, { x: left, y, size: 10, font });
  y -= 16;
  page.drawText(`Tenant: ${invoice.tenantName || 'N/A'}`, { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Received from:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(invoice.recipientName || '', { x: left, y, size: 10, font });
  y -= 14;
  page.drawText(invoice.recipientEmail || '', { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Description:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(invoice.description || 'Donation', { x: left, y, size: 10, font });
  y -= 30;

  const currency = (invoice.currency || 'usd').toUpperCase();
  const amount = new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(invoice.amount / 100);
  page.drawText('Amount:', { x: left, y, size: 12, font: boldFont });
  page.drawText(amount, { x: 200, y, size: 12, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 40;

  page.drawText('This receipt is auto-generated by Harvest for tax purposes.', { x: left, y: 50, size: 8, font, color: rgb(0.6, 0.6, 0.6) });
  page.drawText('theharvest.app', { x: left, y: 35, size: 8, font, color: rgb(0.6, 0.6, 0.6) });

  return pdf.save();
}

// ─── Helper: generate annual receipt PDF ──────────────────────────────────
interface DonorData {
  name: string;
  email: string;
  total: number;
  donations: { date: Date; amount: number; description: string }[];
}

async function generateAnnualReceiptPDF(donor: DonorData, year: number): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  const left = 50;
  let y = 800;

  page.drawText('Harvest', { x: left, y, size: 24, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 20;
  page.drawText(`Annual Tax Receipt ${year}`, { x: left, y, size: 12, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 30;

  page.drawText('Donor:', { x: left, y, size: 10, font: boldFont });
  y -= 16;
  page.drawText(donor.name || donor.email, { x: left, y, size: 10, font });
  y -= 14;
  page.drawText(donor.email, { x: left, y, size: 10, font });
  y -= 30;

  page.drawText('Date', { x: left, y, size: 9, font: boldFont });
  page.drawText('Description', { x: 180, y, size: 9, font: boldFont });
  page.drawText('Amount', { x: 450, y, size: 9, font: boldFont });
  y -= 16;

  for (const d of donor.donations) {
    if (y < 100) break;
    page.drawText(d.date.toLocaleDateString('en-US'), { x: left, y, size: 9, font });
    page.drawText((d.description || 'Donation').slice(0, 35), { x: 180, y, size: 9, font });
    page.drawText(`$${(d.amount / 100).toFixed(2)}`, { x: 450, y, size: 9, font });
    y -= 14;
  }

  y -= 20;
  const totalStr = `$${(donor.total / 100).toFixed(2)}`;
  page.drawText('Total for year:', { x: 350, y, size: 12, font: boldFont });
  page.drawText(totalStr, { x: 450, y, size: 12, font: boldFont, color: rgb(0.83, 0.63, 0.23) });
  y -= 40;

  page.drawText('This document serves as your official tax receipt for the year specified.', { x: left, y: 50, size: 8, font, color: rgb(0.6, 0.6, 0.6) });
  page.drawText('theharvest.app', { x: left, y: 35, size: 8, font, color: rgb(0.6, 0.6, 0.6) });

  return pdf.save();
}

// ─── Helper: upsert contact ──────────────────────────────────────────────────
async function upsertContact(opts: {
  tenantId: string;
  email: string;
  firstName?: string;
  lastName?: string;
  userId?: string;
  type?: 'donor' | 'member' | 'both';
}): Promise<string> {
  const { tenantId, email } = opts;
  const existing = await db.collection('contacts')
    .where('email', '==', email)
    .where('tenantId', '==', tenantId)
    .limit(1).get();

  if (!existing.empty) {
    const doc = existing.docs[0];
    const data = doc.data();
    const update: Record<string, any> = { updatedAt: admin.firestore.FieldValue.serverTimestamp() };
    if (opts.userId) update.userId = opts.userId;
    if (opts.type === 'donor' && data.type === 'member') update.type = 'both';
    else if (opts.type === 'member' && data.type === 'donor') update.type = 'both';
    else if (opts.type === 'both') update.type = 'both';
    await doc.ref.update(update);
    return doc.id;
  }

  const ref = await db.collection('contacts').add({
    firstName: opts.firstName || '',
    lastName: opts.lastName || '',
    email,
    phone: '',
    type: opts.type || 'member',
    userId: opts.userId || '',
    tenantId,
    totalDonated: 0,
    lastDonationAt: null,
    memberSince: opts.type === 'member' ? admin.firestore.FieldValue.serverTimestamp() : null,
    notes: '',
    tags: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    createdBy: 'system',
  });
  return ref.id;
}

// ─── 1. onUserCreated ──────────────────────────────────────────────────────────────
export const onUserCreated = functions.auth.user().onCreate(async (user) => {
  console.log(`onUserCreated: ${user.uid} (${user.email})`);

  await new Promise(resolve => setTimeout(resolve, 5000));

  const userDoc = await db.collection('users').doc(user.uid).get();
  if (!userDoc.exists) {
    console.log(`onUserCreated: No Firestore doc for ${user.uid} yet — will be caught by backfill`);
    return;
  }

  const userData = userDoc.data()!;
  const tenantId = userData.tenantId;
  if (!tenantId) {
    console.log(`onUserCreated: ${user.email} has no tenantId — skipping`);
    return;
  }

  const [firstName, ...lastNameParts] = (user.displayName || userData.firstName || '').split(' ');
  const lastName = lastNameParts.join(' ') || userData.lastName || '';

  const contactId = await upsertContact({
    tenantId,
    email: user.email || '',
    firstName: firstName || '',
    lastName,
    userId: user.uid,
    type: 'member',
  });

  console.log(`onUserCreated: CRM contact ${contactId} for ${user.email} in tenant ${tenantId}`);
});

// ─── 2. onPartnershipPayment ───────────────────────────────────────────────────────
export const onPartnershipPayment = functions.https.onRequest(async (req, res) => {
  if (req.method !== 'POST') {
    res.status(405).send('Method Not Allowed');
    return;
  }

  const stripeKey = process.env.STRIPE_SECRET_KEY;
  const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;
  if (!stripeKey || !webhookSecret) {
    console.error('onPartnershipPayment: Missing Stripe env vars');
    res.status(500).send('Stripe not configured');
    return;
  }

  const stripe = new Stripe(stripeKey);
  const sig = req.headers['stripe-signature'] as string;

  let event: any;
  try {
    event = stripe.webhooks.constructEvent(req.rawBody!, sig, webhookSecret);
  } catch (err: any) {
    console.error('onPartnershipPayment: Signature verification failed:', err.message);
    res.status(400).send('Invalid signature');
    return;
  }

  if (event.type !== 'payment_intent.succeeded') {
    res.json({ received: true, ignored: true });
    return;
  }

  const pi = event.data.object;
  const meta = pi.metadata || {};

  if (meta.type !== 'partnership') {
    res.json({ received: true, ignored: 'non-partnership' });
    return;
  }

  const tenantId = meta.tenantId;
  const donorEmail = pi.receipt_email || meta.donorEmail || '';
  const amount = pi.amount_received || pi.amount || 0;

  if (!tenantId || !donorEmail) {
    res.json({ received: true, skipped: 'missing metadata' });
    return;
  }

  const contactId = await upsertContact({ tenantId, email: donorEmail, type: 'donor' });

  await db.collection('contacts').doc(contactId).update({
    totalDonated: admin.firestore.FieldValue.increment(amount),
    lastDonationAt: admin.firestore.FieldValue.serverTimestamp(),
  });

  await db.collection('contactActivities').add({
    contactId, type: 'donation',
    description: 'Partnership donation via Stripe',
    amount,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    createdBy: 'system',
  });

  const tenantDoc = await db.collection('tenants').doc(tenantId).get();
  const tenantName = tenantDoc.data()?.name || tenantDoc.data()?.displayName || '';
  const contactDoc = await db.collection('contacts').doc(contactId).get();
  const cData = contactDoc.data() || {};
  const recipientName = `${cData.firstName || ''} ${cData.lastName || ''}`.trim() || donorEmail;

  const receiptNumber = `R-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
  await db.collection('tenants').doc(tenantId).collection('invoices').add({
    type: 'donation_receipt', recipientName, recipientEmail: donorEmail,
    amount, currency: pi.currency || 'usd', description: 'Partnership donation',
    relatedId: pi.id, receiptNumber,
    issuedAt: admin.firestore.FieldValue.serverTimestamp(),
    tenantName, pdfUrl: null, status: 'pending',
  });

  res.json({ received: true, processed: true, contactId });
});

// ─── 3. backfillCRMContacts ─────────────────────────────────────────────────────────
export const backfillCRMContacts = functions.https.onCall(async (_data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Must be signed in');
  }

  const uid = context.auth.uid;
  const email = context.auth.token.email || '';
  const userDoc = await db.collection('users').doc(uid).get();
  const userData = userDoc.data();

  const isSuperAdmin = SUPER_ADMIN_EMAILS.includes(email)
    || userData?.role === 'super_admin'
    || context.auth.token.superAdmin === true;

  if (!isSuperAdmin) {
    throw new functions.https.HttpsError('permission-denied', 'Super admin only');
  }

  const usersSnap = await db.collection('users').get();
  let created = 0, updated = 0, skipped = 0;

  for (const doc of usersSnap.docs) {
    const data = doc.data();
    const tenantId = data.tenantId;
    const userEmail = data.email || '';
    if (!tenantId || !userEmail) { skipped++; continue; }

    const existingSnap = await db.collection('contacts')
      .where('email', '==', userEmail)
      .where('tenantId', '==', tenantId)
      .limit(1).get();

    const wasNew = existingSnap.empty;
    const [firstName, ...lastNameParts] = (data.displayName || data.firstName || '').split(' ');
    await upsertContact({
      tenantId, email: userEmail,
      firstName: firstName || '',
      lastName: lastNameParts.join(' ') || '',
      userId: doc.id,
      type: 'member',
    });

    if (wasNew) created++;
    else updated++;
  }

  const result = { created, updated, skipped, total: usersSnap.size };
  console.log('backfillCRMContacts: Done', result);
  return result;
});

// ─── 4. generateSingleReceipt ───────────────────────────────────────────────────────
export const generateSingleReceipt = functions.firestore
  .document('tenants/{tenantId}/invoices/{invoiceId}')
  .onCreate(async (snap, context) => {
    const invoiceData = snap.data();
    const tenantId = context.params.tenantId;
    const invoiceId = context.params.invoiceId;

    try {
      const pdfBytes = await generateReceiptPDF(invoiceData);
      const bucket = getBucket();
      const filePath = `tenants/${tenantId}/invoices/${invoiceId}.pdf`;
      const file = bucket.file(filePath);
      await file.save(Buffer.from(pdfBytes), { metadata: { contentType: 'application/pdf' } });
      // Private file — downloaded on demand via an authenticated signed URL, never public.
      await snap.ref.update({ pdfPath: filePath, pdfUrl: null, status: 'generated', updatedAt: admin.firestore.FieldValue.serverTimestamp() });
      console.log(`generateSingleReceipt: PDF generated for ${invoiceId}`);
    } catch (error: any) {
      console.error(`generateSingleReceipt: Failed for ${invoiceId}:`, error?.message || error);
    }
  });

// ─── 5. generateAnnualReceipts ──────────────────────────────────────────────────────
export const generateAnnualReceipts = functions.https.onCall(async (data, context) => {
  if (!context.auth) throw new functions.https.HttpsError('unauthenticated', 'Must be signed in');

  const { year, tenantId } = data;
  if (!year || !tenantId) throw new functions.https.HttpsError('invalid-argument', 'year and tenantId required');

  const uid = context.auth.uid;
  const email = context.auth.token.email || '';
  const userDoc = await db.collection('users').doc(uid).get();
  const userData = userDoc.data();

  const isSuperAdmin = SUPER_ADMIN_EMAILS.includes(email)
    || userData?.role === 'super_admin'
    || context.auth.token.superAdmin === true;

  if (!isSuperAdmin && userData?.tenantId !== tenantId) {
    throw new functions.https.HttpsError('permission-denied', 'Access denied to this tenant');
  }

  const startOfYear = new Date(Number(year), 0, 1);
  const endOfYear = new Date(Number(year), 11, 31, 23, 59, 59);

  const invoicesSnap = await db.collection('tenants').doc(tenantId)
    .collection('invoices')
    .where('type', '==', 'donation_receipt')
    .where('issuedAt', '>=', startOfYear)
    .where('issuedAt', '<=', endOfYear)
    .get();

  if (invoicesSnap.empty) {
    return { generated: 0, sent: 0, totalDonors: 0, message: 'No donation invoices found for this year' };
  }

  const tenantDoc = await db.collection('tenants').doc(tenantId).get();
  const tenantName = tenantDoc.data()?.name || tenantDoc.data()?.displayName || '';

  const donorsMap = new Map<string, DonorData>();
  for (const doc of invoicesSnap.docs) {
    const inv = doc.data();
    const donorEmail = inv.recipientEmail;
    if (!donorEmail) continue;
    if (!donorsMap.has(donorEmail)) {
      donorsMap.set(donorEmail, { name: inv.recipientName || donorEmail, email: donorEmail, total: 0, donations: [] });
    }
    const donor = donorsMap.get(donorEmail)!;
    donor.total += inv.amount;
    donor.donations.push({
      date: inv.issuedAt?.toDate ? inv.issuedAt.toDate() : new Date(),
      amount: inv.amount,
      description: inv.description || 'Donation',
    });
  }

  const bucket = getBucket();
  let sent = 0, generated = 0;
  const failedEmails: string[] = [];

  for (const [donorEmail, donor] of donorsMap) {
    try {
      const pdfBytes = await generateAnnualReceiptPDF(donor, Number(year));
      const filePath = `tenants/${tenantId}/annual-receipts/${year}/${donorEmail}.pdf`;
      const file = bucket.file(filePath);
      await file.save(Buffer.from(pdfBytes), { metadata: { contentType: 'application/pdf' } });
      // Donors receive the PDF as the email attachment below — the stored copy stays private.
      generated++;

      const resendKey = process.env.RESEND_API_KEY;
      if (resendKey) {
        const resend = new Resend(resendKey);
        const pdfBase64 = Buffer.from(pdfBytes).toString('base64');
        const { error } = await resend.emails.send({
          from: 'Harvest <noreply@theharvest.app>',
          to: donorEmail,
          subject: `Annual Tax Receipt ${year} — ${tenantName || 'Harvest'}`,
          html: `<p>Dear ${donor.name},</p><p>Please find your annual tax receipt attached for the year ${year}.</p><p>Total donations: <strong>$${(donor.total / 100).toFixed(2)}</strong></p><p>Thank you for your partnership!</p><br><p>— ${tenantName || 'Harvest'}</p>`,
          attachments: [{ filename: `tax-receipt-${year}.pdf`, content: pdfBase64 }],
        });
        if (error) { failedEmails.push(donorEmail); } else { sent++; }
      }
    } catch (err: any) {
      console.error(`generateAnnualReceipts: Failed for ${donorEmail}:`, err?.message || err);
      failedEmails.push(donorEmail);
    }
  }

  const result = { generated, sent, totalDonors: donorsMap.size, failedEmails };
  console.log('generateAnnualReceipts: Done', result);
  return result;
});

// ─── 6. addChurchBilling ───────────────────────────────────────────────────────────
export const addChurchBilling = functions.https.onCall(async (data, context) => {
  if (!context.auth) throw new functions.https.HttpsError('unauthenticated', 'Must be signed in');

  const { tenantId, churchId, churchName } = data;
  if (!tenantId || !churchId) throw new functions.https.HttpsError('invalid-argument', 'tenantId and churchId required');

  const uid = context.auth.uid;
  const email = context.auth.token.email || '';
  const userDoc = await db.collection('users').doc(uid).get();
  const userData = userDoc.data();

  const isSuperAdmin = SUPER_ADMIN_EMAILS.includes(email)
    || userData?.role === 'super_admin'
    || context.auth.token.superAdmin === true;

  if (!isSuperAdmin && userData?.tenantId !== tenantId) {
    throw new functions.https.HttpsError('permission-denied', 'Access denied to this tenant');
  }

  const stripeKey = process.env.STRIPE_SECRET_KEY;
  if (!stripeKey) throw new functions.https.HttpsError('failed-precondition', 'Stripe not configured');
  const stripe = new Stripe(stripeKey);

  const tenantDoc = await db.collection('tenants').doc(tenantId).get();
  const tenantData = tenantDoc.data();
  if (!tenantData) throw new functions.https.HttpsError('not-found', 'Tenant not found');

  const subscriptionId = tenantData?.stripeSubscriptionId;
  if (!subscriptionId) throw new functions.https.HttpsError('failed-precondition', 'Tenant has no active Stripe subscription');

  const subItem = await stripe.subscriptionItems.create({
    subscription: subscriptionId,
    price_data: {
      currency: 'usd',
      unit_amount: 1500,
      recurring: { interval: 'month' },
      product_data: {
        name: `Additional Church: ${churchName || churchId}`,
        metadata: { tenantId, churchId, type: 'per_church' },
      },
    } as any,
    metadata: { tenantId, churchId, type: 'per_church' },
  });

  await db.collection('churches').doc(churchId).update({
    stripeSubscriptionItemId: subItem.id,
    billingAmount: 1500,
    billingAddedAt: admin.firestore.FieldValue.serverTimestamp(),
  });

  return { success: true, subscriptionItemId: subItem.id };
});

// ─── 7. removeChurchBilling ─────────────────────────────────────────────────────────
export const removeChurchBilling = functions.firestore
  .document('churches/{churchId}')
  .onDelete(async (snap, context) => {
    const churchData = snap.data();
    if (!churchData) return;

    const subscriptionItemId = churchData.stripeSubscriptionItemId;
    if (!subscriptionItemId) return;

    const stripeKey = process.env.STRIPE_SECRET_KEY;
    if (!stripeKey) { console.error('removeChurchBilling: STRIPE_SECRET_KEY not configured'); return; }
    const stripe = new Stripe(stripeKey);

    try {
      await stripe.subscriptionItems.del(subscriptionItemId);
      console.log(`removeChurchBilling: Removed ${subscriptionItemId} for church ${context.params.churchId}`);
    } catch (err: any) {
      console.error(`removeChurchBilling: Failed to remove ${subscriptionItemId}:`, err?.message || err);
    }
  });

// ─── 8. telegramWebhook ──────────────────────────────────────────────────────────────
export const telegramWebhook = functions
  .runWith({ secrets: ['TELEGRAM_BOT_TOKEN', 'MIMO_API_KEY'] })
  .https.onRequest(async (req, res) => {
  if (req.method !== 'POST') {
    res.status(405).send('Method Not Allowed');
    return;
  }

  const botToken = process.env.TELEGRAM_BOT_TOKEN;
  const mimoKey = process.env.MIMO_API_KEY;

  if (!botToken) {
    console.error('telegramWebhook: TELEGRAM_BOT_TOKEN not configured');
    res.status(500).send('Bot not configured');
    return;
  }

  const update = req.body;
  const message = update?.message;
  if (!message) {
    res.json({ ok: true });
    return;
  }

  const chatId = message.chat?.id;
  const text = (message.text || '').trim();
  const username = message.from?.username || '';

  if (!chatId || !text) {
    res.json({ ok: true });
    return;
  }

  const sendMessage = async (replyText: string) => {
    try {
      await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chat_id: chatId, text: replyText }),
      });
    } catch (err) {
      console.error('telegramWebhook: sendMessage failed:', err);
    }
  };

  // Handle /start {uid} deep link
  if (text.startsWith('/start')) {
    const uid = text.split(' ')[1]?.trim();

    if (!uid) {
      await sendMessage('Welcome to Harvest AI Assistant! Please use the Connect button in your Harvest admin settings to activate your assistant.');
      res.json({ ok: true });
      return;
    }

    try {
      const userDoc = await db.collection('users').doc(uid).get();
      if (!userDoc.exists) {
        await sendMessage('User not found. Please try again from your Harvest admin settings.');
        res.json({ ok: true });
        return;
      }

      const userData = userDoc.data()!;
      if (!userData.hasAIAssistant) {
        await sendMessage('You don\'t have an AI Assistant subscription. Please subscribe from your Harvest admin settings at theharvest.app');
        res.json({ ok: true });
        return;
      }

      await db.collection('users').doc(uid).update({
        telegramChatId: String(chatId),
        telegramUsername: username || null,
        aiAssistantConnected: true,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      });

      await sendMessage('Your Harvest AI Assistant is now connected! Ask me anything about your ministry, members, events, or how to use Harvest. What can I help you with today?');
    } catch (err: any) {
      console.error('telegramWebhook: /start handler error:', err?.message || err);
      await sendMessage('Something went wrong. Please try again.');
    }

    res.json({ ok: true });
    return;
  }

  // Handle regular messages — find user by chatId
  try {
    const usersSnap = await db.collection('users')
      .where('telegramChatId', '==', String(chatId))
      .limit(1)
      .get();

    if (usersSnap.empty) {
      await sendMessage('Your Telegram account is not connected to a Harvest account. Please connect from your admin settings at theharvest.app');
      res.json({ ok: true });
      return;
    }

    const userData = usersSnap.docs[0].data();

    if (!userData.hasAIAssistant || !userData.aiAssistantConnected) {
      await sendMessage('Your AI Assistant subscription is no longer active. Please check your subscription at theharvest.app');
      res.json({ ok: true });
      return;
    }

    if (!mimoKey) {
      await sendMessage('AI service is not configured. Please contact support.');
      res.json({ ok: true });
      return;
    }

    // Fetch tenant context
    let tenantContext = '';
    if (userData.tenantId) {
      try {
        const tenantDoc = await db.collection('tenants').doc(userData.tenantId).get();
        if (tenantDoc.exists) {
          const t = tenantDoc.data()!;
          tenantContext = `Ministry: ${t.name || userData.tenantId}. Plan: ${t.plan || 'unknown'}.`;
        }
      } catch { /* non-fatal */ }
    }

    const systemPrompt = `You are a personal AI assistant for a ministry leader using Harvest, a church management platform. ${tenantContext} Be helpful, concise, and faith-affirming. Help with ministry management, sermon preparation, member care, events, and using Harvest features.`;

    const aiResponse = await fetch('https://token-plan-cn.xiaomimimo.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${mimoKey}`,
      },
      body: JSON.stringify({
        model: 'mimo-v2.5',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: text },
        ],
        max_tokens: 1000,
      }),
    });

    if (!aiResponse.ok) {
      console.error('telegramWebhook: Mimo API error:', aiResponse.status);
      await sendMessage('Sorry, I couldn\'t process your request right now. Please try again in a moment.');
      res.json({ ok: true });
      return;
    }

    const aiData = await aiResponse.json() as any;
    const reply = aiData?.choices?.[0]?.message?.content || 'I could not generate a response. Please try again.';
    await sendMessage(reply);
  } catch (err: any) {
    console.error('telegramWebhook: Message handler error:', err?.message || err);
    await sendMessage('Sorry, something went wrong. Please try again.');
  }

  res.json({ ok: true });
});
